language: rust
rust: nightly
os:
  - linux
  - osx
cache: cargo
sudo: false
before_script:
  - rustup component add rustfmt
script:
  - cargo build
  - cargo test -p mutagen-core # run unit tests first
  - cargo test -p mutagen-selftest # run integration tests
  - cargo test # run all (other) tests

  # run executable cargo-mutagen on test project
  - pushd examples/simple
  - cargo run --bin cargo-mutagen --package cargo-mutagen

  # check format
  - cargo fmt -- --check
